### ISSUE TITLE
Can't edit, update or change any element 

### ISSUE THREAD

**Issue by eae710** [sjarvela/kloudspeaker#107]
I can't edit, update or change any element (permission, group, user or any other) only I can add new elements. I'm admin user.
![screenshot_1](https://cloud.githubusercontent.com/assets/472642/12648842/72639258-c5a1-11e5-967a-8fe0085d3907.png)

**Comment by sjarvela** [comment]
Your server does not seem to understand or support the REST syntax, for some reason your web server says the url does not exist etc.

Is the url otherwise ok? Could you check your PHP error log if there are any errors?

There is service param option (https://github.com/sjarvela/kloudspeaker/wiki/Client-configuration-options#service-param-service-param) for cases where PHP server does not support the way url paths are handled, but there was a problem which is fixed in next release.

If it was actually edit you did (even when the error says it was GET), then you need to enable restricted HTTP methods: https://github.com/sjarvela/kloudspeaker/wiki/Backend-configuration-options#limited-http-methods-enable_limited_http_methods

**Comment by eae710** [comment]
Works great!.

> "If it was actually edit you did (even when the error says it was GET), then you need to enable restricted HTTP methods: https://github.com/sjarvela/kloudspeaker/wiki/Backend-configuration-options#limited-http-methods-enable_limited_http_methods"

Thanks a lot!
