### ISSUE TITLE
Slow mySQL queries in ItemProvider load()

### ISSUE THREAD

**Issue by b-and-p** [sjarvela/kloudspeaker#124]
Issue:
In `backend\include\filesystem\ItemIdProvider.class.php` , `load()` method has this code:

```
$pathFilter = "path REGEXP '^" . $db->string($this->itemQueryPath($parent)) . "[^/]+[/]?$'";
```

The generated query (`select id, path from mollify_item_id where path REGEXP '^133:/Foo/Bar/67 Food Technology/[^/]`) is very slow, I get results in 4.5 seconds

I changed it to:

```
$pathFilter = "path LIKE '" . $db->string($this->itemQueryPath($parent)) . "%' AND NOT path = '".  
$db->string($this->itemQueryPath($parent)) . "'";
```

which produces this query:

```
select id, path from mollify_item_id where path LIKE '133://Foo/Bar/67 Food Technology/%'
AND NOT
 path = '133://Foo/Bar/67 Food Technology/'
```

which returns same results in 0.0469 seconds.

I propose review of mySQL queries and possible update for better performance

**Comment by sjarvela** [comment]
That indeed sounds quite heavy query.

The point with the regexp query in load is to fetch all items that are under this particular folder, but _not_ in any level below.

Correct me if I'm wrong, but your suggestion seems to load everything beneath the given folder, not being exactly same.

Of course, with such huge performance difference, it might be even faster to filter rows manually after the DB query, but I'd primarily look for pure-SQL solution.

**Comment by sjarvela** [comment]
One possibility would be to reduce the set for which the regexp is run, with a subquery with "like", as suggested here: http://stackoverflow.com/questions/2740006/mysql-regexp-performance-question

**Comment by b-and-p** [comment]
> The point with the regexp query in load is to fetch all items that are under this particular folder, but not in any level below.
> Correct me if I'm wrong, but your suggestion seems to load everything beneath the given folder, not being exactly same.

You are right, but why does it appear to work correctly then on my setup? I see only first level in file manager.

**Comment by sjarvela** [comment]
It works, because the real set of files is based on filesystem. Only the item ids loaded is done based on this query, in this case it loads too much items.

Of course it's not as bad as loading too few, as this would lead into system trying to add missing items, but naturally it would be ideal to load only those that are really in that folde. Theoretically there might be lots of files in lower lever, which would be loaded unnecessarily.

**Comment by b-and-p** [comment]
Interesting, I have a tree with 64K+ files (PDF documents) and a few hundred folders I suppose, it is strictly a 4 level deep hierarchy (enforced by application), My claim on speed improvement across various levels / folders I have tested stands - I saw a significant speed / responsiveness improvement while browsing the directory. Could it be that even loading all these extra data is much lighter on the system than getting the correct set with mysql REGEXP?

**Comment by sjarvela** [comment]
Yes, that's definitely possible.

I myself cannot get such big differences with execution time on my development environment, so it's hard to test different methods.

However, the solution suggested in the post I mentioned earlier (subquery) might bring the best of both, subquery reducing the set of files and regexp filtering out the right level. I'll try to see if I can get the query right, it would be interesting to see how it performs against the plain "too wide" query. Would you be willing to test it?

**Comment by b-and-p** [comment]
I was also thinking (not tested) about getting the data with `LIKE` as I have, then getting the first level in PHP using `foreach` or something, and see how it compares speed-wise.

I don't mind running some tests when I have time, if you provide some guidance. I have difficulty debugging kloudspeaker - xdebug session gets killed in netbeans, I hardly get any output of `var_dump` or `echo` as well. The system is a bit too advanced for my OOP skills.

**Comment by sjarvela** [comment]
The load actually does that, it makes the query and then uses foreach to store id/path pairs into cache. So it would be possible to filter out items in that part, but I guess there is no point in that. It's just a cache, so that if anyone requests item id for an path, it is there, but otherwise it won't do any harm, only perhaps consumes memory. On the contrary, filtering would only make it slower, as it would have to do some string comparison or regexp evaluation.

However, there are other places where it matters more. For example, function "pathQueryFilter" is used all over system to make queries that hit only items in that level, for example to load comments for items in that particular level only. In this case it is not acceptable to load any extra rows, those would end up in the result set as well...

But function "load" is more crucial, as it is used in view listing every time to preload any item ids there might be needed.

So I was wondering if I should strip out the entire "if" there, using the path now chosen when $recursive is TRUE.

**Comment by sjarvela** [comment]
To continue speculating proper solution to replace all regexps with a) same result set b) good performance, it is absolute requirement to be able to match one level of items.

Most straight forward solution would be to have column that has level number, ie 1 = first level, 2 = second level and so on. But this would mean some logic in store and update, would have to try out what it affects.

Any other solution without touching table structure means identifying level from the path string. Regexp was the "easiest", but seems to be slow. Another way would be to count number of path delimiters ("/"), but somehow I think this wouldn't be any faster.

Any ideas are welcome.

**Comment by sjarvela** [comment]
I've now tested approach that adds new item column, level, which makes it fast to query items on specific level. It looks good now, but needs some further testing.
