### ISSUE TITLE
Can't update to 2.7.14 with backend/update

### ISSUE THREAD

**Issue by dejavuzxy** [sjarvela/kloudspeaker#129]
After downloading the latest version of Kloudspeaker and going to backend/update i receive this error in the update script:
"Error executing queries (ALTER TABLE `mollify_item_id` ADD `level...): Duplicate column name 'level'"

What can be done about it?

**Comment by sjarvela** [comment]
What was the version before updating? The field "level" was added in 2.7.14, so since it now complains about duplicate field "level", it sounds like you already had the column?

**Comment by sjarvela** [comment]
I just made test installation for 2.7.13 and then tried upgrading to 2.7.15, it went without problems. And after that retrying upgrade was not allowed, like expected. So it's difficult to say what went wrong in your case.

Of course you can make the upgrade manually using script "2_6_7-2_7_14.sql" under "db/mysql/update", of course you need to replace your db prefix etc.

**Comment by dejavuzxy** [comment]
Yes, it was from 2.7.13. I don't have "2_6_7-2_7_14.sql", i have "2_6_7-2_7_14.sql".
I still can't update the server.

**Comment by sjarvela** [comment]
> I don't have "2_6_7-2_7_14.sql", i have "2_6_7-2_7_14.sql"

Umm, can't see difference between what you don't and do have...

Anyway, of course you cannot run the script _as is_, because installer would do it as well. It's natural it fails for the first command "ADD level", just like installer.

Instead, run every command individually from top to bottom, fail or not. Result should be the same.

After all, it only adds one column and few indexes for it, and then it populates the "level" field, and finally marks the update done by setting version to 2_7_14.

**Comment by sjarvela** [comment]
Just noticed that ADD INDEX commands don't have table prefix, so this indeed can fail for setups that have prefix. I'll release new version.

**Comment by sjarvela** [comment]
Version 2.7.16 released. If you want to retry update with the new package, you have to drop the field "level" from table "item_id", because it sounds like your first trial might not have finished successfully, and left the field without marking update done.

**Comment by dejavuzxy** [comment]
The last solution worked. I dropped the "Level" field from "item_id" table. After that running the update script normally and it finished it as usually.

Thank you.

**Comment by sjarvela** [comment]
Great!
