### ISSUE TITLE
Insufficient permissions if browser cache is not cleared when logging in as another user

### ISSUE THREAD

**Issue by cheegui** [sjarvela/kloudspeaker#134]
Hi Sjarvela

Thank you for coming out with such a great software.  Kloudspeaker is simply awesome.    

We are getting this error message "kloudspeaker Insufficient permissions" whenever we log out and then log in as another user.    When we clear the browser OR close and relaunch the browser, we don't get the error message.     Apparently, there is some cached contents/credentials that cause the error? 

Thank you once again

**Comment by sjarvela** [comment]
When does this occur? Does it let you log in, or is it some action that causes this?

What are the users like, what permissions do they have?

Does this occur with any users?

**Comment by cheegui** [comment]
It occurred after logging in.   It is harmless in that we could just click the OK button in the Insufficient Permissions window and then proceed.  
We just tested again - login as admin, created a new user, created a folder and assigned folder to user, and then logout as admin, login as new user and we got the Insufficient Permissions message.
We didn't assign User Permissions to the folder.  We use System Permissions - which are :+1: System default
Change password  No
Share files/folder Yes
Filesystem access Read&Write&Delete
Edit file/folder description Yes

We also tested logging as User1, and then logout and login as User2 and still got the error message.

Note that the error message won't appear when we relaunch browser or clear browser cache.

Thank you.

**Comment by cheegui** [comment]
We test-created another user.  This time, we gave it User Permissions: 
Change password No
Share files/folder Yes
Filesystem access Read&Write&Delete
Edit file/folder description Yes
Still got the error after logging in.
Thank you.
![insufficent_permissions2](https://cloud.githubusercontent.com/assets/11359174/15550054/80de64c8-2264-11e6-96c2-7285c28770d4.jpg)

**Comment by sjarvela** [comment]
I cannot make this happen, no matter what kind of user I create. Would it be possible for me to see this in your server, have two test accounts which I could try login with (if so, you can send email with details)?

**Comment by cheegui** [comment]
Hi Sjarvela

It is an internal server but we can open it up to the Internet.   Can we send the IP address to you in an email?  
Thank you so much!

**Comment by sjarvela** [comment]
Yes, you can send it to my email. I'll take a look at it tomorrow.

**Comment by cheegui** [comment]
Hi Sjarvela

Just sent the email to your gmail account. 

Thank you!

**Comment by sjarvela** [comment]
I tested with your site, and at first could not see any problems. But disabling cache did the trick, and I think I know what this is about.

When you log in with user A, you are forwarded to url "/files/aaaaa/", where "aaaaa" is the ID of the folder. Now when user logs out, the url remains there, so that next login will reopen the same view. However, if you log in with a user that does not have this same folder assigned, the error is presented, but it also forwards it to a first valid folder.

So I think the fix is quite easy, just suppress the error in this case, where the initial view ID is not valid for the user. However, what I cannot understand right away, why does the caching matter in this case, that is something I need to find out.

**Comment by sjarvela** [comment]
Fixed
