### ISSUE TITLE
Kloudspeaker not showing on IE and Firefox ESR

### ISSUE THREAD

**Issue by alex-maxime** [sjarvela/kloudspeaker#28]
After installing Kloud Speaker for test in local. Trying to access to it with http://localhost/kloudspeaker/
On IE and Firefox ESR. i only have blank page

**Comment by luke7263** [comment]
Same pb, it only works with Firefox last release and Chrome.
Now I'mcoming upset, I based everything on Kloudspeaker, but my customers won't wait so need to find a more stable solution... Each upgrade is a pain, a whole day spent each time to control everything, I'm really upset, I spent so many days on this solution..

**Comment by sjarvela** [comment]
I've tested Chrome, Firefox, Safari (on desktop and iPhone) and IE 11 (which is pretty much standard on Windows 7) and I can't see any errors.

Please understand that I'm not doing this deliberately, like I said I can't see these errors, hard to avoid them.

So
1) what versions of IE are you using
2) any errors in the console

**Comment by nnmalex** [comment]
Works fine for me in any browser when installed on apache@ubuntu server.

**Comment by sjarvela** [comment]
Hmm, _server_ really should not be relevant browser related issues...

One thing I realized on my development environment: now that require.js is loading modules asynchronosly from plugin folders, it is important to have same URL used in all places.

There is a backend setting "host_public_address" and "customizations_folder_url" that should have the same IP/domain name as used in browser, because these URLs are used in referring to and loading certain resources, like modules. And if they don't match, browsers may consider them different domains, violating same-origin policy security rule, and rejecting them.

For example, if you have configured "host_public_address" to "http://server_name/kloudspeaker" and then use browser with "http://192.168.1.2/kloudspeaker", even if they really point to same server, browser could not know it and refuse to load modules.

This could show as application not starting, and console should show something like "Script error for [MODULE NAME]".

**Comment by nnmalex** [comment]
Could be also file access permissions issue on the server.

**Comment by sjarvela** [comment]
Not really, any server issue would show on any browser. Browsers simply cannot overcome server related issues.

If there is a browser issue, it can be seen in browser console. If someone can actually see this error, please post it here, it is required to make any assumptions whether it is configuration issue, or some bug.

**Comment by alex-maxime** [comment]
okay, i remember IE have some errors. I will make a screenshot this monday at work

**Comment by alex-maxime** [comment]
![000853_2015-06-16 09_27_41-phonecontrol - recordings navigator - internet explorer](https://cloud.githubusercontent.com/assets/3592127/8177949/f253a0d8-1409-11e5-91b0-1453f3c071c4.png)

This is what i have with IE
To translate : 

```
Several definitions of a property are not allowed in strict mode
File: kloudspeaker.full.min.js, line 25, column: 18838

  "$" Is undefined
File: recordings, line 32, column 4
```

**Comment by sjarvela** [comment]
Thanks!

Could you change your js into non-minified (ie. use "kloudspeaker.full.js" instead of "...min.js"), the line number does not help if it is minified. (this is changed in the index.html)

Is it possible for me to access your site (you can email me directly if I can)? What IE version does this occur?

**Comment by sjarvela** [comment]
Also, what is this file "recordings", as it is not part of the installation package? The error seems to be that jQuery has not been initialized, perhaps imported too early, but anyway, not part of the Kloudspeaker package.

**Comment by alex-maxime** [comment]
"recordings" it is because i have installed KloudSpeaker under path "recordings" (http://192.XX.XX.XX/recordings  => //var/www/recordings on my server)

I am sorry i cannot provide you an access because of firewall rules. i need to ask to pen an access before. it may take a while.

i have unfortunately the same error after switching to non minimified version. here some screenshots

![000857_2015-06-17 15_18_02-phonecontrol - recordings navigator - internet explorer](https://cloud.githubusercontent.com/assets/3592127/8207950/12a95b9c-1505-11e5-9633-c8744abc58fb.png)

My Config:
![000859_2015-06-17 15_22_56-c__users_maxime_appdata_local_temp_fz3temp-1_index html geremya ilp9-2015-inst](https://cloud.githubusercontent.com/assets/3592127/8207964/2263bc8a-1505-11e5-894c-ac2ad7271d04.png)
It seems like jquery it is not initialized ($)

**Comment by sjarvela** [comment]
OK, thanks. In that case it makes sense that the jquery is not loaded if the full.js fails, as it's part of that file.

Unfortunately, line 17683 does not have any explanation for the error. In the version 2.6.12 the line is this:

```
title: spec.options[k]
```

taken from this snippet

```
    if (spec.options) {
        opts = [];
        $.each(kloudspeaker.helpers.getKeys(spec.options), function(i, k) {
            opts.push({
                key: k,
                title: spec.options[k]
            });
        });
    }
```

This part has not changed for ages, and there should be no strict mode violation in this part.

Could you get still more info:

1) what version of kloudspeaker do you have?
2) what version of IE do you use?
3) could open the IE inspector to see what exactly is the error line(s)? They might be interpreted differently

As I said, I have tested with IE 11, so it's strange why wouldn't it get the same errors (as strict mode did not exist in versions prior to IE 10)?

**Comment by sjarvela** [comment]
Just digged out old Win XP virtual machine, which has IE 8, and tested with it. It had few errors which I fixed here: https://github.com/sjarvela/kloudspeaker/commit/a33b4ca4f83464a2249c8f0fe0c8c68622d2e3c2

Although I have no plans supporting IE8, with these fixes I was able to get it running on IE8.

Both of these changes are not related to new functionality, and are not be related to latest releases. I doubt these are even important, but perhaps using quotes around "default" might be worth adding. The other is for detecting history support, and is not needed for modern browsers.

Anyway, now I have tested IE8 and IE11, both running without errors. Haven't decided what is my "official" support for IE, but since Windows 7 is lowest supported version of Windows by Microsoft. And since Win7 pushes IE 11 with Windows Update, I doubt I will use much effort to support earlier IE versions.

**Comment by alex-maxime** [comment]
Hi,

Thanks for your reactivity.
For those question 
1) what version of kloudspeaker do you have? 
             I have version 2.6.11 (rev. 23)
2) what version of IE do you use?  
             I am using IE 11 on Windows 7
3) could open the IE inspector to see what exactly is the error line(s)? They might be interpreted  
             Ok, error come from line 17683 and o IE inspector, at this line, i have : 
![000861_2015-06-22 10_06_28-f12](https://cloud.githubusercontent.com/assets/3592127/8277785/69a0989c-18c6-11e5-9935-400b88ce6ca4.png)

**Comment by sjarvela** [comment]
Oh yes, that's due to double assignment (property "show" is reassigned, which is forbidden in strict mode), but this should be fixed in later releases. You could try removing line 17681, and see if it's the only problem?

**Comment by alex-maxime** [comment]
Good Job, It works now on IE 11. Jus made an update.
Problem seems to be solved.

Thanks for your help.
