### ISSUE TITLE
Copy drop down for "read only"

### ISSUE THREAD

**Issue by nnmalex** [sjarvela/kloudspeaker#31]
If user has a "read only" access he can still see "Copy" in drop down menu. Truing to Copy in this case results to an error message.

**Comment by sjarvela** [comment]
The reason actually is, that system cannot know what kind of access the user has until he has chosen the target. He might have explicitly overridden higher permissions to some folder.

**Comment by nnmalex** [comment]
Wouldn't it be better to check permission for enclosing folders (one level down) when rendering the parent folder?

**Comment by sjarvela** [comment]
It really wouldn't matter. Of course system knows the permission user has for the copied item, but it's not about that. To copy item, user needs only read permission to the copied item, and sure system checks that this is met. It's easy, as user wouldn't even see it, if he didn't.

But copying also requires write permission to the target folder, and this is not known until it is chosen

**Comment by nnmalex** [comment]
Yeah, it makes sense to me now. 

The reason I'm asking is I plan to use your script (buying appropriate license of course) to share company's content with customers outside of organization who will never have write access so they really don't need to see the copy button.

**Comment by sjarvela** [comment]
Okay, you meant in the folder selector dialog? Then yes, that's more or less what I've considered (First I assumed you meant rendering the original file list).

Currently I'm rewriting different parts as separate modules, and this allows creating separate permission module, which could even cache permissions for a while whenever permissions are resolved, this may make it bit lighter, but it could indeed do permission checking on background as well.

But nevertheless, this would not remove the original topic, that the copy action cannot be ruled out until some target is applied

**Comment by nnmalex** [comment]
To be sure we are speaking about the same thing here is the screenshot of what I meant:

http://prntscr.com/7hc0rp

**Comment by sjarvela** [comment]
Getting back on this, the problem is obvious with the copy button. System cannot know if user can or cannot copy it _anywhere_, it would literally have to examine every single folder there is, to know if that button can be shown. So that is not an option.

You would need some kind of special feature, something like "don't show copy button if user is in group X" etc. But that would be custom feature for your site, not something that is included in the app itself, I suppose.

Sure it would be doable with simple client plugin (perhaps would require some hook added to make it possible to customize available actions), but I couldn't promise any schedules when this could happen.

**Comment by nnmalex** [comment]
Understood. That doesn't cause much problems so I guess can be closed.
