### ISSUE TITLE
Enhancement: Download Resume Support

### ISSUE THREAD

**Issue by crashmaxed** [sjarvela/kloudspeaker#34]
I was thinking of using Kloudspeaker as a way to distribute very large files (10GB) to end users.  The catch is that many of the end users have internet connections which are unstable at times.  To this end the platform we use has to support resuming of file download.  Would it be possible at all to add this?

**Comment by sjarvela** [comment]
Certainly possible, and I agree this is important.

There are few things that make this difficult, but I'll investigate this as soon as possible.

**Comment by sjarvela** [comment]
First I read this as upload resume support, as it requires some more effort. For download resume support, I was under impression it requires only range download support (ie. client responsible for downloads can ask for partial ranges instead of whole file), and this already is there.

How exactly are you expecting to use resume download feature?

**Comment by crashmaxed** [comment]
I'm not sure exactly what release I was running back in June when I opened this.  Back then no matter what browser I used there was no pause and resume support on downloads.  Maybe there was some issue with range requests as all pause and resumes would just cause the download to start back at the beginning.  I just tested again today on 2.7.9 and it does appear to be working now.
