### ISSUE TITLE
Read-only interface when underlying UNIX permissions are insufficient?

### ISSUE THREAD

**Issue by chewi** [sjarvela/kloudspeaker#62]
I think it would be handy if the interface could present itself as read-only when Kloudspeaker can determine in advance that it won't have permission to write to the given directory due to insufficient underlying UNIX permissions. We're coupling our use of Kloudspeaker with locked-down SFTP access so we're relying more on UNIX permissions than Kloudspeaker ones.

**Comment by sjarvela** [comment]
Added in commit https://github.com/sjarvela/kloudspeaker/commit/8525e9d502cf953a327ceea1cadace3daf8d2c02

Although it is kind of weird setup that even when filesystem is readonly in OS level, admin would grant write permissions in Kloudspeaker, does not make much sense. But anyway, I've added initial support for filesystem being able to report itself as read-only.

There is still one aspect that can be confusing: in permission inspector, system will still show system permissions as they are set, and it will show incorrect permissions if filesystem is readonly. This would have to be added explicitly so that inspector would know there is something that overrides the basic permission inheritance rules.

**Comment by chewi** [comment]
Many thanks! I'll try this next week.

We're basically setting up the file structure with Chef and we want to have as little manual intervention as possible so we're just assigning write access as the system default and letting the filesystem do the rest. As I said, we need this anyway to cover the SFTP side of things.

**Comment by sjarvela** [comment]
Released in 2.7.4

**Comment by chewi** [comment]
Just tried it, it works great. Thanks again!
