### ISSUE TITLE
Error when clicking user on Users page then nothing happens

### ISSUE THREAD

**Issue by chewi** [sjarvela/kloudspeaker#67]
I've only just started using Kloudspeaker but if I remember correctly, the list of folders assigned to that user is supposed to appear below. As of 2.7.5, I'm getting this instead.

```
Uncaught ReferenceError: plugins is not defined
  a._showUserDetails @ kloudspeaker.min.js:24
  k.init.j.table.onHilight @ kloudspeaker.min.js:24
  (anonymous function) @ kloudspeaker.min.js:21
  ia.event.dispatch @ kloudspeaker.min.js:7
  ia.event.add.r.handle @ kloudspeaker.min.js:7
```

I know a minified backtrace isn't great, sorry about that.

**Comment by jasonPaddy** [comment]
chewi, I have actually noticed this issue too.
issue is with kloudspeaker.min.js (version 2.7.5)
I replaced it with kloudspeaker.min.js from version 2.7.3 and it works.
since I have submitted few issues regarding 2.7.5 and Sam fixed them in source code.

I guess we just need to wait Sam to release 2.7.6 then.

**Comment by chewi** [comment]
Okay but I don't think this one has been fixed yet as far as I can tell.

**Comment by sjarvela** [comment]
One module dependency was missing, fixed

**Comment by sjarvela** [comment]
in 2.7.6
