### ISSUE TITLE
User with no upload priviledges can upload files thru Quick share

### ISSUE THREAD

**Issue by spxjet** [sjarvela/kloudspeaker#70]
Hello,

Just found out that an user with no upload priviledges can get to the upload screen thru the top "setting "icon and then "Quick share" or "Share"
![1](https://cloud.githubusercontent.com/assets/14998136/10311300/d5b9c25c-6c4e-11e5-95bd-ed594545fdb3.png)
![2](https://cloud.githubusercontent.com/assets/14998136/10311301/d5bbfc7a-6c4e-11e5-90df-05cdb492f514.png)
![3](https://cloud.githubusercontent.com/assets/14998136/10311299/d5b8ba24-6c4e-11e5-8a6d-3f28346dd2d7.png)

**Comment by chewi** [comment]
Does it actually allow them to upload or can they only see the screen?

**Comment by spxjet** [comment]
It allow them to upload.

**Comment by sjarvela** [comment]
That's right, user without write permission should not be able to share uploads. Once you get to the upload screen, anyone can upload, which is right, but the user should not be able to create such share in first place.

At the moment there is separate permission controlling whether user can share items, but it does not check write permissions.

I'll change this.

**Comment by chewi** [comment]
That doesn't sound like good security. Shouldn't the permission to upload be separate from the ability to view the upload screen? How does this affect WebDAV?

**Comment by sjarvela** [comment]
Share feature is meant for sharing file/folder for anyone, so anyone who has the link, can do the action that share is meant for. Ie. if you create download share, anyone with the link can download, no need to have account for the system. Same goes for upload share, it grants upload permission (but not browse/download permission). Upload is meant for "upload your documents here" -kind of use, without recipient needing/having to know where it goes, and not revealing what else has been uploaded there.

You are not supposed to give that link if you don't want grant access. Of course, there are options to restrict the access, for example with password, but still this is about _anonymous_ access, not user account permissions. That's why there is permission for controlling who can share and what.

**Comment by sjarvela** [comment]
And WebDAV has nothing to do with this. WebDAV is accessed with user credentials, share is not.

**Comment by chewi** [comment]
Thanks for the explanation. I wasn't familiar with the share feature.

**Comment by sjarvela** [comment]
In 2.7.7
