### ISSUE TITLE
Folder copy tries to create the folder twice in destination

### ISSUE THREAD

**Issue by ghost** [sjarvela/kloudspeaker#72]
Version 2.7.6 (rev. 34)
When copying a folder (my_folder) to a new destination (test), I get an error : 
RESPONSE error {0:999, 1:Unexpected server error, 2:500} PHP error #2, mkdir(): No such file or directory (backend/include/filesystem/LocalFilesystem.class.php:321)
After debugging a bit, it shows that the copy tries to create the folder
test/my_folder/my_folder
but as mkdir is not recursive by default, it fails.

If I replace backend/include/filesystem/LocalFilesystem.class.php:321 by 
@mkdir($to, 0755, true); 
the copy works well (**but I have the double folder in the destination**)

If I select multiple folders to copy, everything is fine.

**Comment by sjarvela** [comment]
Copy function constructed target folder wrong, it added folder name twice, which lead into path that cannot be created. The API for copy was changed at some point, and single folder copy was not updated, it seems.

Fixed in https://github.com/sjarvela/kloudspeaker/commit/8b783ee1e3b48cd89e43110aaad27dc025417550

**Comment by sjarvela** [comment]
In 2.7.7

**Comment by ghost** [comment]
Thanks !
