### ISSUE TITLE
VLC Plugin

### ISSUE THREAD

**Issue by kosmynin** [sjarvela/kloudspeaker#81]
How can I activate the experimental VLC plugin?
Adding a VLC viewer to the config php crashes the system.

**Comment by sjarvela** [comment]
Again, this does not help without error logs. VLC viewer is registered just the same as any other viewer, but it has not been maintained as it most likely is not candidate for official viewer (requires browser plugin etc).

**Comment by chewi** [comment]
What formats are you trying to play? Browser support for these kinds of plugins is generally on life support these days. You should look towards native `<video>` and `<audio>` tags.

**Comment by kosmynin** [comment]
i'm trying to play *.mkv files

**Comment by chewi** [comment]
Apparently Chrome can play Matroska files natively because it is a variant of WebM but it might depend on what MIME type the web server advertises and it'll obviously also depend on what codecs were used. Someone needs to write the code to render the `<video>` tag first though! If it were me, I'd just mount the share using the WebDAV plugin and open the file with VLC normally.

**Comment by kosmynin** [comment]
I now tried to set up the Webdav Plugin instead of the VLC plugin but get an 404 error when opening the root dir in the web interface.
